
# DeepSeek API Key
deepseek:
    api:
      key: sk-46db862e6703426d835b9bf3563b1178
      url: https://api.deepseek.com/v1/chat/completions

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/essay_checker
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
